<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "beneficiario".
 *
 * @property integer $id
 * @property integer $personaid
 * @property string $estado
 * @property integer $cantidad_hijo
 * @property string $edad_por_hijo
 * @property string $aliasModel
 */
abstract class Beneficiario extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'beneficiario';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['personaid'], 'required'],
            [['personaid', 'cantidad_hijo'], 'integer'],
            [['estado', 'edad_por_hijo'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'personaid' => 'Personaid',
            'estado' => 'Estado',
            'cantidad_hijo' => 'Cantidad Hijo',
            'edad_por_hijo' => 'Edad Por Hijo',
        ];
    }




}
