<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "hijo".
 *
 * @property integer $cantidad_hijo
 * @property string $edad_por_hijo
 * @property integer $beneficiarioid
 *
 * @property \app\models\Beneficiario $beneficiario
 * @property string $aliasModel
 */
abstract class Hijo extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'hijo';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['cantidad_hijo', 'beneficiarioid'], 'integer'],
            [['beneficiarioid'], 'required'],
            [['edad_por_hijo'], 'string', 'max' => 100],
            [['beneficiarioid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Beneficiario::className(), 'targetAttribute' => ['beneficiarioid' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'cantidad_hijo' => 'Cantidad Hijo',
            'edad_por_hijo' => 'Edad Por Hijo',
            'beneficiarioid' => 'Beneficiarioid',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBeneficiario()
    {
        return $this->hasOne(\app\models\Beneficiario::className(), ['id' => 'beneficiarioid']);
    }




}
